config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
    path("tickets/", include("tickets.urls")),
    path("", include("pages.urls")),
    path("temperatures/", include("temps.urls")),
    path("instructions/", include("instructions.urls")),
    path("emails/", include("emails.urls")),
    path("exampels/", include("exampels.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView, LoginView
from .views import HomeView


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

tickets/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('detailTickets/<int:pk>/', views.TicketDetailView.as_view(), name='detail_ticket'),

    path('listTickets/<int:pk>/', views.UserTicketListView.as_view(), name='list_tickets'),
    path('createTickets/', views.BaseView.as_view(), name='create_tickets'),
]

tickets/models.py
from django.db import models
from django.conf import settings


class Ticket(models.Model):
    STATUS_CHOICES = (
        ('open', 'Open'),
        ('close', 'Close'),
    )
    PRIORITY_CHOICES = (
        ('instantaneous', 'Instantaneous'),
        ('medium', 'Medium'),
        ('low', 'Low'),
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='tickets'
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Comment', related_name='ticket_comments')
    labels = models.ManyToManyField('Label', related_name='tickets')

    read_by_superuser = models.BooleanField(default=False)
    read_by_user = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Attachment(models.Model):
    ticket = models.ForeignKey('Ticket', on_delete=models.CASCADE, related_name='attachments')
    file = models.FileField(upload_to='ticket_attachments/')

    def __str__(self):
        return str(self.file)


class Comment(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.created_at}'


class Label(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name

tickets/forms.py
from django import forms
from .models import Comment, Ticket
from multiupload.fields import MultiFileField, MultiMediaField, MultiImageField


class CloseTicketForm(forms.Form):
    STATUS_CHOICES = (
        ('open', 'باز'),
        ('close', 'بسته'),
    )
    close_reason = forms.ChoiceField(choices=STATUS_CHOICES, label='Status')


class TicketForm(forms.ModelForm):
    attachment = MultiFileField(min_num=1, max_num=5,
                                max_file_size=1024 * 1024 * 5)  # تعریف فیلد attachment به عنوان غیرضروری

    class Meta:
        model = Ticket
        fields = ('title', 'description', 'priority', 'attachment',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

tickets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.core.mail import send_mail
from django.contrib import messages
from django.views import View

from .models import Ticket, Comment, Attachment
from .forms import CommentForm, TicketForm


class TicketDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        ticket = get_object_or_404(Ticket, id=pk)
        comments = Comment.objects.filter(ticket=ticket)
        comment_form = CommentForm()
        admin_user = get_user_model().objects.filter(is_staff=True).first()

        if request.user.is_superuser:
            ticket.read_by_superuser = False
        else:
            ticket.read_by_user = False

        ticket.save()

        attachments = ticket.attachments.all()

        return render(request, 'tickets/ticket_detail.html',
                      {
                          'ticket': ticket,
                          'comments': comments,
                          'comment_form': comment_form,
                          'admin_user': admin_user,
                          'attachments': attachments,
                      })

    def post(self, request, pk):
        ticket = get_object_or_404(Ticket, id=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            if ticket.status == 'open':
                comment = comment_form.save(commit=False)
                comment.ticket = ticket
                comment.user = request.user
                comment.save()

                new_status = request.POST.get('status')
                if request.user.is_superuser:
                    ticket.status = new_status
                    ticket.read_by_user = True
                    ticket.read_by_superuser = False
                else:
                    ticket.status = 'open'
                    ticket.read_by_user = False
                    ticket.read_by_superuser = True
                ticket.save()

        return HttpResponseRedirect(reverse('detail_ticket', args=[pk]))


def send_admin_notification(ticket):
    # پیاده‌سازی تابع ارسال اطلاعیه به ادمین، به عنوان مثال ارسال ایمیل
    subject = 'New Ticket Submission'
    message = f'A new ticket has been submitted with the title: {ticket.title}'
    from_email = 'hamze_Nasirii@yahoo.com'
    to_email = 'amir_hamze64@yahoo.com'
    send_mail(subject, message, from_email, [to_email])


class BaseView(LoginRequiredMixin, FormView):
    template_name = 'tickets/ticket_form.html'
    form_class = TicketForm
    success_url = reverse_lazy('create_tickets')

    def form_valid(self, form):
        ticket = form.save(commit=False)
        ticket.status = 'open'
        ticket.user = self.request.user
        ticket.read_by_user = 'True'
        ticket.save()

        attachments = self.request.FILES.getlist('attachment')
        for attachment in attachments:
            Attachment.objects.create(ticket=ticket, file=attachment)

        messages.success(self.request, 'تیکت با موفقیت ارسال شد.')
        return super().form_valid(form)

    def form_invalid(self, form):
        field_errors = form.errors.items()
        error_message = "Form submission failed. Please check the form for errors."
        return self.render_to_response(
            self.get_context_data(form=form, field_errors=field_errors, error_message=error_message)
        )


class UserTicketListView(ListView):
    model = Ticket
    template_name = 'tickets/user_ticket_list.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Ticket.objects.filter(status='open')
        else:
            return Ticket.objects.filter(user=self.request.user)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #
    #
    #     return context

tickets/templates/tickets/ticket_detail.html
{% extends 'base.html' %}

{% block title %}
    جزئیات تیکت
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title mb-2 float-left">جزئیات تیکت</h3>
            </div>
            <div class="card-body ">
                <table class="table table-striped">
                    <tr>
                        <th>عنوان:</th>
                        <td>{{ ticket.title }}</td>
                        <th>تاریخ ایجاد:</th>
                        <td>{{ ticket.created_at }}</td>
                    </tr>
                    {#                    <tr>#}
                    {#                        <th>توضیحات:</th>#}
                    {#                        <td>{{ ticket.description }}</td>#}
                    {#                    </tr>#}
                    <tr>
                        <th>اولویت:</th>
                        <td>{{ ticket.priority }}</td>
                        <th>ضمیمه:</th>
                        <td>
                            {% if attachments %}
                                {% for attachment in attachments %}
                                    <a href="{{ attachment.file.url }}">{{ forloop.counter }}. دانلود ضمیمه</a><br>
                                {% endfor %}
                            {% else %}
                                ندارد
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th>توضیحات:</th>
                        <td>{{ ticket.description }}</td>
                    </tr>
                </table>
                <br><br>
                {% if user.is_superuser or ticket.user == user %}
                    {% if comments %}
                        <h4>گفتگو:</h4>

                        {% for comment in comments %}
                            <div class="comment-box {% if comment.user.is_staff %}admin-comment{% else %}user-comment{% endif %}">
                                <p>{{ comment.text }}</p>
                                <p>By {{ comment.user.get_full_name }} at {{ comment.created_at }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}


                    {% if ticket.status == 'open' %}
                        <h4>پاسخ:</h4>
                        <form method="post" action="{% url 'detail_ticket' pk=ticket.pk %}">
                            {% csrf_token %}
                            {% if not user.is_superuser %}
                                <p>
                                    <textarea name="text" cols="100" rows="10" required id="id_text"></textarea>
                                </p>
                            {% else %}
                                <p>
                                    <textarea name="text" cols="100" rows="10" id="id_text"></textarea>
                                </p>
                                <select name="status" id="id_status" style="font-size: 18px; width: 200px;">
                                    <option value="open">باز</option>
                                    <option value="close">بسته</option>
                                </select>
                            {% endif %}
                            <button type="submit" class="btn btn-outline-success">ارسال پاسخ</button>
                        </form>
                    {% endif %}
                {% else %}
                    <p> شما به این تیکت دسترسی ندارید</p>
                {% endif %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#id_status').on('change', function () {
                if ($(this).val() === 'close') {
                    $('#id_text').val('این تیکت توسط {{user.get_full_name}} بسته شد');
                } else {
                    $('#id_text').val('');
                }
            });
        });
    </script>
    <style>
        .comment-box {
            border: 1px solid;
            margin-bottom: 10px;
            padding: 10px;
            border-radius: 5px;
        }

        .admin-comment {
            border-color: #f00;
            background-color: #ffe6e6;
        }

        .user-comment {
            border-color: #00f;
            background-color: #e6e6ff;
        }
    </style>
{% endblock %}

tickets/templates/tickets/ticket_form.html
{% extends 'base.html' %}

{% block title %}
    <title>Ticket Form</title>
{% endblock %}

{% block content %}

    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title mb-3 float-left">ایجاد تیکت</h3>
            </div>
            <div class="card-body">
                <h1>ایجاد تیکت </h1>
                <form method="post" action="{% url 'create_tickets' %}" enctype="multipart/form-data">

                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-row">
                            <div class="form-group col-md-12 text-left">
                                <label for="title">موضوع:</label>
                                <input type="text" name="title" id="title" class="form-control" required>
                            </div>

                            <div class="form-group col-md-12 text-left">
                                <label for="description">توضیحات:</label>
                                <textarea name="description" id="description" class="form-control" required></textarea>
                            </div>

                            <div class="form-group col-md-4 text-left">
                                <label for="priority">الویت:</label>
                                <select name="priority" id="priority" class="form-control">
                                    <option value="low">کم</option>
                                    <option value="medium">متوسط</option>
                                    <option value="high">زیاد</option>
                                </select>
                            </div>
{#                            <div class="form-group col-md-4 text-left">#}
{#                                <label for="attachment">افزودن فایل:</label>#}
{#                                <input type="file" name="attachment" id="id_attachment" class="btn-outline-success">#}
{#                            </div>#}

                            <div class="form-group col-md-4 text-left">
                                <label for="id_attachment">افزودن فایل:</label>
                                <input type="file" name="attachment" id="id_attachment" class="btn-outline-success" multiple="multiple">
                            </div>

                        </div>
                    </div>
                    <button type="submit" class="btn btn-outline-success">ثبت و ارسال تیکت</button>
                    <a href="{% url 'list_tickets' user.id %}">
                        <button type="button" class="btn btn-outline-info">مشاهده تیکت های ارسال شده</button>
                    </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

tickets/templates/tickets/ticket_submission.html
{% extends 'base.html' %}

{% block title %}
    <title>Ticket Submission</title>
{% endblock %}

{% block content %}
    <h1>Ticket Submitted</h1>
    <p>Your ticket has been submitted successfully. An administrator will review it shortly.</p>

{% endblock %}

tickets/templates/tickets/user_ticket_list.html
{% extends 'base.html' %}

{% block title %}
    لیست تیکت‌های ارسالی
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title mb-3 float-left">لیست تیکت های ارسالی</h3>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>ردیف</th>
                        {% if request.user.is_superuser %}
                            <th>شماره ملی</th>
                            <th>نام و نام خانوادگی</th>
                        {% endif %}
                        <th>عنوان</th>
                        <th>توضیحات</th>
                        <th>اولویت</th>
                        <th>وضعیت تیکت</th>
                        <th>تاریخ ایجاد</th>
                        <th>عملیات</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ticket in tickets %}
                        {% if ticket.user == request.user or request.user.is_superuser %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                {% if request.user.is_superuser %}
                                    <td>{{ ticket.user.username }}</td>
                                    <td>{{ ticket.user.get_full_name }}</td>
                                {% endif %}
                                <td>{{ ticket.title }}
                                    {% if ticket.user == request.user and ticket.read_by_user and ticket.status == 'open' %}
                                        <span class="right badge badge-danger">پیغام جدید</span>
                                    {% elif request.user.is_superuser and ticket.read_by_superuser %}
                                        <span class="right badge badge-danger">پیغام جدید</span>
                                    {% endif %}
                                </td>
                                <td>{{ ticket.description|slice:":20" }}</td>
                                <td>{{ ticket.priority }}</td>
                                <td>{{ ticket.status }}</td>
                                <td>{{ ticket.created_at }}</td>
                                <td>
                                    <a href="{% url 'detail_ticket' ticket.id %}" class="btn btn-outline-primary">نمایش
                                        جزئیات</a>
                                </td>
                            </tr>
                        {% endif %}
                    {% empty %}
                        <tr>
                            <td colspan="5">هیچ تیکتی موجود نیست.</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}