config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
    path("tickets/", include("tickets.urls")),
    path("", include("pages.urls")),
    path("temperatures/", include("temps.urls")),
    path("instructions/", include("instructions.urls")),
    path("emails/", include("emails.urls")),
    path("exampels/", include("exampels.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instructions/urls.py
from django.urls import path

from .views import (
    InsListView,
    InsCreateView,
    InsUpdateView,
    ins_delete,
    InsListViewDeleted,
    InsDetailView,
    InstructionDownloadView,
    SelfInsListView,
    InstructionRestoreView,
    CreateTagsView,
    delete_tag,
    get_suggested_tags,
)

urlpatterns = [
    path("delete_tag/<int:pk>/", delete_tag, name="delete_tag"),
    path("listCreateTags/", CreateTagsView.as_view(), name="create_tags"),
    path("listIns/", InsListView.as_view(), name="instruction_list"),
    path("selflistIns/", SelfInsListView.as_view(), name="self_instruction_list"),
    path(
        "listInsDeleted/", InsListViewDeleted.as_view(), name="instruction_list_deleted"
    ),
    path(
        "<int:instruction_id>/download/",
        InstructionDownloadView.as_view(),
        name="instruction_download",
    ),
    path("get_suggested_tags/", get_suggested_tags, name="get_suggested_tags"),
    path("createIns/", InsCreateView.as_view(), name="instruction_create"),
    path("updateIns/<int:pk>", InsUpdateView.as_view(), name="instruction_update"),
    path(
        "restore/<int:instruction_id>/",
        InstructionRestoreView.as_view(),
        name="restore_instruction",
    ),
    path("detailIns/<int:pk>", InsDetailView.as_view(), name="instruction_detail"),
    path("deleteIns/<int:pk>", ins_delete, name="instruction_delete"),
]

pages/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView, LoginView
from .views import HomeView


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

instructions/models.py
from django.db import models
from django.conf import settings
import os


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="ادرس  آی پی")


class Instruction(models.Model):
    TYPE_CHOICES = (
        ("instruction", "دستورالعمل"),
        ("journal", "مقاله"),
        ("appreciation", "تشویق نامه"),
        ("text", "متن"),
        ("video", "ویدئو"),
        ("audio", "صوت"),
        ("image", "تصویر"),
    )
    STATUS_CHOICES = (
        ("drf", "Draft"),
        ("pub", "Published"),
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="instructions"
    )
    type = models.CharField(max_length=12, choices=TYPE_CHOICES, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    number = models.CharField(max_length=50, unique=True, null=True, blank=True)
    # pdf_file = models.FileField(verbose_name='Instruction PDF', upload_to='instructions/pdf_files/', null=True,
    #                             blank=True)
    # image_file = models.ImageField(verbose_name='Instruction Image', upload_to='instructions/image_files/', null=True,
    #                                blank=True)
    download_count = models.PositiveIntegerField(default=0)
    hits = models.ManyToManyField(
        IPAddress, blank=True, related_name="hits", verbose_name="بازدیدها"
    )

    for_behvarz = models.BooleanField(default=False)
    for_expert = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    tags = models.ManyToManyField("Tag", blank=True, null=True)

    status = models.CharField(
        max_length=3, choices=STATUS_CHOICES, null=True, blank=True, default="drf"
    )

    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-datetime_updated", "-datetime_created"]

    def __str__(self):
        return self.title

    def increment_download_count(self):
        self.download_count += 1
        self.save()


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Attachment(models.Model):
    ins_attach = models.ForeignKey(
        "Instruction", on_delete=models.CASCADE, related_name="instruction_attach"
    )
    file = models.FileField(upload_to="Instruction_attach/", null=True, blank=True)
    file_name = models.CharField(max_length=255, default="فایل")
    file_size = models.PositiveIntegerField(default=0)
    download_count = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        self.file_name = os.path.basename(self.file.name)
        self.file_size = self.file.size

        if self.pk is None:  # در صورتی که رکورد جدید ایجاد می‌شود
            self.download_count = 0  # تنظیم تعداد دانلود به صفر

        super().save(*args, **kwargs)

    def increase_download_count(self):
        self.download_count += 1
        self.save(update_fields=["download_count"])

    def __str__(self):
        return self.file_name

instructions/forms.py
from django import forms
from .models import Tag

from jalali_date.fields import JalaliDateField, SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime

from .models import Instruction, Attachment
from accounts.models import CustomUser


class CreateTagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = {"name"}


class InsChangeForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset=CustomUser.objects.all(), widget=forms.HiddenInput(), disabled=True
    )
    selected_attachments = forms.ModelMultipleChoiceField(
        queryset=Attachment.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(),
        label="فایل‌های ضمیمه",
    )
    tags = forms.ModelChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
        required=False,
    )

    class Meta:
        model = Instruction
        fields = {
            "type",
            "user",
            "status",
            "title",
            "description",
            "number",
            "for_behvarz",
            "for_expert",
            "tags",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields[
                "selected_attachments"
            ].queryset = self.instance.instruction_attach.all()


class InstructionForm(forms.ModelForm):
    tags = forms.ModelChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
        required=False,
    )
    attachments = forms.ModelMultipleChoiceField(
        queryset=Attachment.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Instruction
        fields = {"type", "status"}

        widgets = {
            "type": forms.Select(attrs={"class": "form-control"}),
            "start_date": forms.DateInput(
                attrs={"class": "form-control", "placeholder": "YYYY-MM-DD"}
            ),
            "end_date": forms.DateInput(
                attrs={"class": "form-control", "placeholder": "YYYY-MM-DD"}
            ),
            "status": forms.Select(attrs={"class": "form-control"}),
            "q": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "جستجو"}
            ),
        }

        # def __init__(self, *args, **kwargs):
        #     super().__init__(InstructionForm, self).__init(*args, **kwargs)
        #     self.fields['start_date'] = JalaliDateField(label='date', widget=AdminJalaliDateWidget)
        #
        #     self.fields['start_date'] = SplitJalaliDateTimeField(label='start_date', widget=AdminSplitJalaliDateTime)

instructions/templates/instructions/ins_create.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}

{% block title %}
    ارسال محتوا جدید
{% endblock %}

{% block load_css %}

{% endblock %}

{% block content %}

    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title mb-3 float-left">ارسال محتوا</h3>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-row">

                        <div class="form-group col-md-4">
                            <label for="id_type">نوع محتوا:</label>
                            <select name="type" class="form-control" id="id_type" required>
                                {% for type in form.type %}
                                    {{ type }}
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group col-md-4">
                            <label for="id_number">شماره محتوا:</label>
                            <input type="text" class="form-control" name="number" maxlength="10" id="id_number"
                                   required>
                        </div>

                        <div class="form-group col-md-4">
                            <label for="id_title">موضوع:</label>
                            <input type="text" class="form-control" name="title" maxlength="200" required
                                   id="id_title">
                        </div>

                        <div class="form-group col-md-12">
                            <label for="id_description">توضیحات:</label>
                            <textarea name="description" class="form-control" cols="100" rows="10" required
                                      id="id_description"></textarea>
                        </div>

                        {#                        <div class="col-md-3">#}
                        {#                            <div class="form-group">#}
                        {#                                <label for="id_pdf_file">ارسال فایل PDF:</label>#}
                        {#                                <input type="file" class="form-control" name="pdf_file" id="id_pdf_file"#}
                        {#                                       onchange="changeBorderColor(this)">#}
                        {#                            </div>#}
                        {#                        </div>#}

                        {#                        <div class="col-md-3">#}
                        {#                            <div class="form-group">#}
                        {#                                <label for="id_image_file">ارسال تصویر:</label>#}
                        {#                                <input type="file" class="form-control" name="image_file" accept="image/*"#}
                        {#                                       id="id_image_file" onchange="changeBorderColor(this)">#}
                        {#                            </div>#}
                        {#                        </div>#}

                        <div class="col-md-3">
                            <div class="form-group col-md-4 text-left">
                                <label for="id_attachment">افزودن فایل:</label>
                                <input type="file" name="attachment" id="id_attachment" class="btn-outline-success"
                                       multiple="multiple">
                            </div>
                        </div>

                        <div class="form-group col-md-2">
                            <div class="form-check">
                                <br>
                                <input type="checkbox" class="form-check-input" name="for_behvarz" id="id_for_behvarz">
                                <label class="form-check-label" for="id_for_behvarz">نمایش به بهورزان</label>
                            </div>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="for_expرت" id="id_for_expert">
                                <label class="form-check-label" for="id_for_expert">نمایش به کارشناسان</label>
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="id_tags">تگ‌ها:</label>
                            <input type="text" class="form-control" name="tags" maxlength="200" id="id_tags"
                                   autocomplete="off">
                            <div id="suggestions" class="suggestions">
                                <!-- اینجا تگ‌ها نمایش داده می‌شوند -->
                            </div>
                        </div>

                        {#                        <div class="form-group col-md-2">#}
                        {#                            <label for="id_tags">تگ‌ها:</label>#}
                        {#                            <input type="text" class="form-control" name="tags" maxlength="200"#}
                        {#                                   id="id_tags"#}
                        {#                                   autocomplete="off">#}
                        {#                            <div id="suggestions" class="suggestions">#}
                        {#                                <!-- اینجا تگ‌ها نمایش داده می‌شوند -->#}
                        {#                            </div>#}
                        {#                        </div>#}

                        <div class="form-group col-md-3">
                            <label for="id_status">وضعیت محتوا:</label>
                            <select name="status" class="form-control" id="id_status">
                                <option value="">---------</option>
                                <option value="drf" selected>Draft</option>
                                <option value="pub">Published</option>
                            </select>
                        </div>

                        <div id="selectedTags" name="selected_tags" class="form-group col-md-12">
                            <!-- اینجا تگ‌های انتخاب شده نمایش داده می‌شوند -->
                            {% for tag in selected_tags %}
                                <div class="tag">
                                    {{ tag }}
                                    <span class="remove-tag" onclick="removeTag('{{ tag|escapejs }}')">×</span>
                                </div>
                            {% endfor %}
                        </div>
                        {#                        <input type="hidden" name="selected_tags" id="selected_tags_input">#}

                    </div>


                    <button type="submit" class="btn btn-success">ذخیره</button>
                    <span> <a href="/instructions/listIns/" class="btn btn-info">انصراف</a> </span>
                </form>
            </div>
        </div>
    </div>
    <script>
        function changeBorderColor(input) {
            var validFormats = ['pdf', 'jpg', 'jpeg', 'png'];
            var fileFormat = input.value.split('.').pop().toLowerCase();

            if (validFormats.includes(fileFormat)) {
                input.style.borderColor = 'green';
            } else {
                input.style.borderColor = '';
            }
        }

        async function addTagToDOM(tagName) {
            var addedTagsContainer = document.getElementById('addedTags');
            var tagElement = document.createElement('div');
            tagElement.className = 'tag';
            tagElement.innerText = tagName;
            addedTagsContainer.appendChild(tagElement);
        }

        var addedTags = []; // لیست تگ‌های اضافه شده

        function tagAlreadyAdded(tagName) {
            return addedTags.includes(tagName);
        }

        function removeTag(tagName) {
            addedTags = addedTags.filter(tag => tag !== tagName);
        }

        async function addTag(tagName, tagID) {
            addedTags.push({
                name: tagName,
                id: tagID
            });
            console.log('Received Tag ID:', tagID);
            console.log('Received Tag Name:', tagName);

            if (tagAlreadyAdded(tagName)) {
                alert('تگ قبلاً افزوده شده است.');
                return;
            }

            var tagsContainer = document.getElementById('selectedTags');
            var tagElement = document.createElement('div');
            tagElement.className = 'tag';
            tagElement.innerText = tagName;

            // اضافه کردن دکمه حذف
            var removeButton = document.createElement('span');
            removeButton.className = 'remove-tag';
            removeButton.innerText = '×';
            removeButton.addEventListener('click', function () {
                removeTag(tagName);
                tagElement.remove(); // حذف تگ از DOM
            });

            tagElement.appendChild(removeButton);
            tagsContainer.appendChild(tagElement);

            var inputId = document.createElement('input');
            inputId.type = 'hidden';
            inputId.name = 'tag_ids';
            inputId.value = tagID;

            document.forms[0].appendChild(inputId);
            // افزودن تگ به ورودی hidden
            var selectedTagsInput = document.createElement('input');
            selectedTagsInput.type = 'hidden';
            selectedTagsInput.name = 'selected_tags';
            selectedTagsInput.value += tagName + ','; // اضافه کردن تگ به لیست تگ‌ها
            tagsContainer.appendChild(selectedTagsInput);
            document.getElementById('id_tags').value = ''; // این خط مقدار ورودی را بازنشانی می‌کند
        }

        var currentTagName = ''; // تعریف متغیر گلوبال

        document.getElementById('id_tags').addEventListener('input', function () {
            var input = this;
            var query = input.value;
            if (query.length >= 1) {
                fetch('/instructions/get_suggested_tags/?query=' + query)
                    .then(response => response.json())
                    .then(data => {
                        var suggestionsDiv = document.getElementById('suggestions');
                        suggestionsDiv.innerHTML = '';
                        data.suggestions.forEach(function (suggestion) {
                            var suggestionElement = document.createElement('div');
                            suggestionElement.innerText = suggestion.name;
                            suggestionElement.addEventListener('click', function () {
                                // اگر کلیک شد، تگ را اضافه کنید
                                addTag(suggestion.name, suggestion.id); // اینجا suggestion.id  نمایانگر آی‌دی تگ است
                                input.value = '';
                                suggestionsDiv.innerHTML = '';
                            });
                            suggestionsDiv.appendChild(suggestionElement);
                        });
                    });
            } else {
                document.getElementById('suggestions').innerHTML = '';
            }
        });
    </script>


    <style>
        input:invalid,
        select:invalid {
            border-color: red;
        }

        .remove-tag {
            color: red;
            cursor: pointer;
            font-size: 1.3em; /* یا هر اندازه دلخواه دیگر */
            font-weight: bold; /* نمایش علامت حذف بصورت بولد شده */
            padding-left: 0px; /* تغییر فاصله به سمت راست */
            padding-right: 0px; /* تغییر فاصله به سمت چپ */
            margin-right: 4px; /* تغییر فاصله به سمت راست */
            margin-left: 0px; /* تغییر فاصله به سمت چپ */
        }

        .tag {
            display: inline-block;
            margin-right: 5px;
            background-color: #f2f2f2;
            padding: 5px 10px;
            border-radius: 5px; /* تنظیم شعاع لبه‌های چهارگوش */
        }
    </style>

{% endblock %}

instructions/templates/instructions/ins_delete.html
{% extends 'base.html' %}
{% load persian_translation_tags %}

{% block title %}
{% endblock %}

{% block content %}
    <div class="col-md-8 text-center mx-auto">
        <div class="card card-danger">
            <div class="card-header">
                <h3 class="card-title mb-0 float-left">حذف دستورالعمل</h3>
            </div>
            <div class="card-body py-4">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p class="py-2">آیا از حذف مقاله "{{ instruction.title }}" با شماره نامه "{{ instruction.number|translate_numbers }}" اطمینان
                        دارید؟</p>
                    <button type="submit" class="btn btn-danger">حذف {{ instruction.type }}</button>
                    <span>  <a href="{% url 'instruction_list' %}" class="btn btn-info">انصراف</a> </span>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

instructions/templates/instructions/ins_detail.html
{% extends 'base.html' %}
{% load ratings %}
{% load persian_translation_tags %}
{% load jalali_tags %}


{% block title %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h3>جزئیات محتوای {{ instruction.get_type_display }} با موضوع "{{ instruction.title }}"</h3>
            <hr>
            <span>
            {% if not user.user_type == 'behvarz' and instruction.user == user and not user.is_superuser %}
                {% if instruction.status == 'pub' %}
                    محتوا منتشر شده و قابلیت حذف و ویرایش وجود ندارد.
                {% endif %}
            {% endif %}
                {% if instruction.status == 'drf' and instruction.user == user or user.is_superuser %}
                    <a class="text-green" href="{% url 'instruction_update' instruction.id %}">ویرایش</a>
                    |
                {% endif %}
                {% if instruction.status == 'drf' or user.is_superuser or user.user_type == 'manage' and instruction.user == user %}
                    {% if instruction.is_active or user.is_superuser %}
                        <a class="text-danger" href="{% url 'instruction_delete' instruction.id %}"> حذف</a>
                    {% endif %}
                {% endif %}
                {% if not instruction.is_active and user.is_superuser %}
                    <a href="{% url 'restore_instruction' instruction.id %}"
                       class="badge badge-primary">بازیابی محتوا</a>
                {% endif %}
                {#                <a class="text-info" href="{% url 'self_instruction_list' %}">بازگشت</a>#}
            </span>
            <br>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ش.نامه</th>
                    <th>محبوبیت</th>
                    <th>برای مراقب سلامت</th>
                    <th>برای کارشناس</th>
                    <th>قابل نمایش</th>
                    <th>تاریخ ایجاد</th>
                    <th>تاریخ ویرایش</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ instruction.number|translate_numbers }}</td>
                    <td>{% ratings object %}</td>
                    <td>{% if instruction.for_behvarz %}Yes{% else %}No{% endif %}</td>
                    <td>{% if instruction.for_expert %}Yes{% else %}No{% endif %}</td>
                    <td>{% if instruction.is_active %}Yes{% else %}No{% endif %}</td>
                    <td>{{ instruction.datetime_created|to_jalali:'%Y/%m/%d'|translate_numbers }}</td>
                    <td>{{ instruction.datetime_updated|to_jalali:'%Y/%m/%d'|translate_numbers }}</td>
                </tr>
                </tbody>
            </table>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>تعداد مشاهده</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        {{ instruction.hits.count|translate_numbers }}
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <thead>
                <tr>
                    <th>توضیحات:</th>
                </tr>
                </thead>
                <tr>
                    <td colspan="11">{{ instruction.description }}
                    </td>
                </tr>
                </tfoot>
                <thead>
                <tr>
                    <th>تگ ها:</th>
                </tr>
                </thead>
                <tr>
                    <td colspan="11">
                        {% for tag in tags %}
                            {{ tag.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                </tr>

            </table>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <tbody>
                    <tr>
                        <td>
                        <th>دانلود فایل های ضمیمه:</th>
                        {% for attachment in instruction.instruction_attach.all %}
                            {% with file_name=attachment.file.name %}
                                <br><br>
                                <a href="{{ attachment.file.url }}" download>{{ attachment.file_name }}</a><br>
                                {% if attachment.file %}
                                    <br>
                                    {% with file_url=request.get_host|add:'/'|add:attachment.file.url %}
                                        <img src="https://api.qrserver.com/v1/create-qr-code/?data={{ file_url }}"
                                             alt="QR Code" width="100" height="100">
                                    {% endwith %}
                                {% endif %}
                                تعداد دانلود: {{ attachment.download_count|translate_numbers }}<br>
                                <!-- اضافه کردن این خط -->
                            {% endwith %}
                        {% endfor %}
                        </td>
                        {#                        <td>{% if instruction.viewed %}Yes{% else %}No{% endif %}</td>#}
                    </tr>
                    </tbody>
                </div>
            </div>
        </div>
    </div>
{% endblock %}